@startuml{class.svg}

package "ChangeLogメモ" as ChangeLog <<Database>>
{
}

package "家計簿アプリからエクスポートした.csvファイル" as CSVFile <<Database>> 
{
}

class SyncKakeiboConfig

class ExpenseItem

class CashBook
class ChangeLogMemo
class BuyLog

class CashItem

ChangeLogMemo ..> SyncKakeiboConfig : 設定ファイルを読む

CashBook ..> ExpenseItem : 費目変換
CashItem ..> ExpenseItem : 費目変換

CashBook ..> CSVFile : 読む / 書く
ChangeLogMemo ..> ChangeLog : 読む / 書く

CashBook ..> CashItem : 生成
ChangeLogMemo ..> CashItem : 生成

BuyLog o..> CashItem




@enduml

